### get all pets
GET http://localhost:3000/api/pets
###
http://localhost:3000/api/pets/0
###
http://localhost:3000/api/pets/1
###
http://localhost:3000/api/pets/2
###
http://localhost:3000/api/pets/-2
###
http://localhost:3000/api/pets/500
###
http://localhost:3000/api/pets/3

###
### create pet
POST http://localhost:3000/api/pets
Content-Type: application/json

{
  "age": 5,
  "kind": "Giraffe",
  "name": "Long Neck"
}

### create pet
PATCH http://localhost:3000/api/pets/2
Content-Type: application/json

{
  "name": "Shiny"
}

### delete pet
DELETE http://localhost:3000/api/pets/6

